---

- name: Install NFS Subdirectory External Provisioner
  kubernetes.core.helm:
    name: nfs-subdir-external-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: default
    create_namespace: true
    values:
      nfs:
        server: "{{ nfs_server }}"
        path: "{{ nfs_path }}"
    
- name: Set nfs-client as the default StorageClass
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: nfs-client
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"

- name: Set local-path NOT to be the default StorageClass
  kubernetes.core.k8s:
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: local-path
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"