---
- name: Enabling EPEL Repository on RHEL based systems
  yum:
    name: epel-release
    state: latest
  when: ansible_distribution in ['AlmaLinux', 'CentOS', 'RedHat', 'Rocky']

- name: Add Helm repository for nfs-subdir-external-provisioner
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  when: inventory_hostname == 'localhost' or inventory_hostname == '127.0.0.1'

- name: Add Rancher Helm repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable
  when: inventory_hostname == 'localhost' or inventory_hostname == '127.0.0.1'