---
- name: Install collections from requirements file
  ansible.builtin.command:
    cmd: ansible-galaxy collection install -r "{{ role_path }}/files/install-freeipa-requirements.yaml"
  register: install_result
  changed_when: "'Installing' in install_result.stdout"

- name: Install k3sadm collection version '1.0'
  ansible.builtin.command:
    cmd: ansible-galaxy collection install --collection=k3sadm --version=1.0
  register: install_result
  changed_when: "'Installing' in install_result.stdout"