---
- name: Install collections from requirements file
  ansible.builtin.command:
    cmd: ansible-galaxy collection install -r "{{ role_path }}/files/install-freeipa-requirements.yaml"
  register: install_result
  changed_when: "'Installing' in install_result.stdout"

# Variables
vars:
  k3sadm_version: "1.2.0"

- name: Install k3sadm collection
  ansible.galaxy.collection:
    name: k3sadm
    version: "{{ k3sadm_version }}"

- name: Verify k3sadm installation
  command: k3sadm --version
  register: k3sadm_version_output
  changed_when: false

- name: Assert k3sadm version
  assert:
    that: k3sadm_version_output.stdout.startswith(k3sadm_version)