apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/latest
    targetRevision: 2.10.2  # Update this to the latest stable version
    helm:
      values: |
        hostname: rancher.home.org
        ingress:
          enabled: false  # Disable default ingress, we'll use Traefik
        tls: external
        privateCA: false  # Set to true if using a private CA
        bootstrapPassword: "passwordhere"  # Change this to a secure password
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-cert
  namespace: cattle-system
spec:
  secretName: rancher-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - rancher.home.org

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-route
  namespace: cattle-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`rancher.home.org`)
    kind: Rule
    services:
    - name: rancher
      port: 80
  tls:
    secretName: rancher-tls
