# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: rancher
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://releases.rancher.com/server-charts/stable'
#     targetRevision: 2.10.2
#     chart: rancher
#     helm:
#       values: |
#         hostname: rancher.home.org
#         replicas: 3
#         bootstrapPassword: password
#         ingress:
#           tls:
#             source: letsEncrypt
#         letsEncrypt:
#           email: tbrigham@hotmail.com
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: cattle-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/latest
    targetRevision: 2.10.2
    helm:
      values: |
        hostname: rancher.home.org
        replicas: 3
        ingress:
          tls:
            source: letsEncrypt
        letsEncrypt:
          email: tbrigham@hotmail.com
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.2.230  # Replace with your desired external IP
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
