apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: 24.0.0  # Use the latest stable version as of February 2025
    chart: traefik
    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true
        deployment:
          replicas: 3
        ports:
          web:
            exposedPort: 80
          websecure:
            exposedPort: 443
        additionalArguments:
          - "--api.dashboard=true"
          - "--api.insecure=true"
        dashboard:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true