---
- name: Create a directory for CA certificates
  file:
    path: /etc/kubernetes/pki/ca/
    state: directory

- name: Copying MITRE_BA_NPE_CA-3.crt
  copy:
    src: "MITRE_BA_NPE_CA-3.crt"
    dest: "/etc/kubernetes/pki/ca/"
    mode: '0644'

- name: Copying MITRE_BA_ROOT.crt
  copy:  
    src: "MITRE_BA_ROOT.crt"
    dest: "/etc/kubernetes/pki/ca/"
    mode: '0644'

- name: Copying ZScaler_Root.crt
  copy:  
    src: "ZScaler_Root.crt"
    dest: "/etc/kubernetes/pki/ca/"
    mode: '0644'

- name: Copy CA certificates to worker nodes
  copy:
    src: /etc/kubernetes/pki/ca/*.crt
    dest: /etc/ssl/certs/ca.crt
    mode: 0644

- name: Restart kubelet service
  service:
    name: kubelet
    state: restarted
